DROP TABLE IF EXISTS urls;

CREATE TABLE  urls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    created_at TIMESTAMP );

DROP TABLE IF EXISTS urlCheck;

CREATE TABLE urlCheck (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    status_code INT,
    title TEXT,
    h1 TEXT,
    description TEXT,
    url_id BIGINT
);
